apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app
spec:
  selector:
    matchLabels:
      app: bully-app
  replicas: 5
  template:
    metadata:
      name: bully-app
      labels:
        name: bully-app
        app: bully-app
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: bully-app-sa
      containers:
        - name: bully-container
          image: bully-app:latest
          imagePullPolicy: Never
          env:
            - name: WEB_PORT
              value: "8080"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ELECTION_TYPE
              value: "normal" #must be either 'normal' or 'improved'


          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 1
            successThreshold: 1