apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app
spec:
  selector:
    matchLabels:
      app: bully-app
  replicas: 4
  template:
    metadata:
      name: bully-app
      labels:
        name: bully-app
        app: bully-app
    spec:
      # serviceAccountName: bully-app-sa
      containers:
        - name: bully-container
          image: ds-group3:v0.0.12
          imagePullPolicy: Never
          # envFrom:
          #   - ConfigMapRef:
          #     name: app-config
          env:
            - name: WEB_PORT
              value: "8080"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # - name: ELECTION_TYPE
            #   valueFrom:
            #     configMapKeyRef:
            #       name: app-config
            #       key: ELECTION_TYPE

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP