apiVersion: v1
kind: Service
metadata:
  name: bully-service
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: bully-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 