---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bully-app-sa
  namespace: default

---
# Permission to patch pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-labeler
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch", "update"]

---
# RoleBinding - Give the ServiceAccount the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bully-app-pod-labeler
  namespace: default
subjects:
- kind: ServiceAccount
  name: bully-app-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-labeler
  apiGroup: rbac.authorization.k8s.io